// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://yourdomain.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://yourdomain.com/support",
            "email": "support@yourdomain.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/healthcheck": {
            "get": {
                "description": "Returns the application health status and dependency checks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/healthcheck/liveness": {
            "get": {
                "description": "Returns whether the process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.LivenessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/healthcheck/readiness": {
            "get": {
                "description": "Returns whether the service is ready to serve traffic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/healthcheck.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/trips": {
            "post": {
                "description": "Creates a new trip draft and initializes chat session state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Create trip draft",
                "parameters": [
                    {
                        "description": "Trip draft payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/trip.CreateTripDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}": {
            "get": {
                "description": "Returns the aggregate trip response for dashboard rendering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get trip details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates trip-level fields collected before confirmation and generation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Update trip draft fields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trip patch payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/trip.PatchTripDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/activities": {
            "post": {
                "description": "Adds a place or event item to the trip and updates dashboard state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Add activity manually",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Manual activity payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/trip.ManualActivityDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/budget": {
            "get": {
                "description": "Returns aggregate trip costs, cashback, bonus, and offer fields.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get budget summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.BudgetSummary"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/chat/messages": {
            "get": {
                "description": "Returns the current chat history attached to a trip planning session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get trip chat history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.ChatResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a user message to the trip planning session and returns AI chat output.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Send planning chat message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Chat message payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/trip.ChatMessageDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.ChatResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/confirm": {
            "post": {
                "description": "Confirms collected fields and generates the master-plan dashboard response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Confirm trip and generate plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/options/hotels": {
            "get": {
                "description": "Returns selected and alternative hotel options for a trip.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get hotel options",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/trip.HotelOption"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/options/hotels/{optionId}/select": {
            "post": {
                "description": "Replaces the currently selected hotel option and recalculates budget.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Select hotel option",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Hotel option ID",
                        "name": "optionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/options/transport": {
            "get": {
                "description": "Returns selected and alternative transport options for a trip.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get transport options",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/trip.TransportOption"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/options/transport/{optionId}/select": {
            "post": {
                "description": "Replaces the currently selected transport option and recalculates budget.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Select transport option",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transport option ID",
                        "name": "optionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/regenerate": {
            "post": {
                "description": "Regenerates trip details from current stored state and chat context.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Regenerate trip plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.TripDetailsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/reviews": {
            "get": {
                "description": "Returns AI-produced review summaries and source links for hotels, places, and events.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get review summaries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/trip.ReviewSummary"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/trips/{tripId}/visa": {
            "get": {
                "description": "Returns visa assistant information for the selected destination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@trip"
                ],
                "summary": "Get visa info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trip ID",
                        "name": "tripId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trip.VisaInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "healthcheck.CheckResult": {
            "type": "object",
            "properties": {
                "latency": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "healthcheck.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/healthcheck.CheckResult"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "healthcheck.LivenessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "healthcheck.ReadinessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "trip.ActivityItem": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "day_label": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "manually_added": {
                    "type": "boolean"
                },
                "price": {
                    "type": "integer"
                },
                "source_link": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "trip.BudgetSummary": {
            "type": "object",
            "properties": {
                "bonus_amount": {
                    "type": "integer"
                },
                "cashback_amount": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "estimated_food_total": {
                    "type": "integer"
                },
                "estimated_local_transport_total": {
                    "type": "integer"
                },
                "events_total": {
                    "type": "integer"
                },
                "grand_total": {
                    "type": "integer"
                },
                "halyk_offer_label": {
                    "type": "string"
                },
                "hotel_total": {
                    "type": "integer"
                },
                "insurance_estimate": {
                    "type": "integer"
                },
                "transport_total": {
                    "type": "integer"
                }
            }
        },
        "trip.ChatMessage": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "structured": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "any"
                    }
                }
            }
        },
        "trip.ChatMessageDTO": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "content": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "trip.ChatResponse": {
            "type": "object",
            "properties": {
                "assistant_hints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.ChatMessage"
                    }
                },
                "missing_fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "trip.CreateTripDTO": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "trip.HotelOption": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "review_link": {
                    "type": "string"
                },
                "selected": {
                    "type": "boolean"
                }
            }
        },
        "trip.ManualActivityDTO": {
            "type": "object",
            "required": [
                "day_label",
                "kind",
                "location",
                "title"
            ],
            "properties": {
                "day_label": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "source_link": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "trip.OfferSummary": {
            "type": "object",
            "properties": {
                "bonus_amount": {
                    "type": "integer"
                },
                "cashback_amount": {
                    "type": "integer"
                },
                "halyk_offer": {
                    "type": "string"
                },
                "highlights": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "trip.PatchTripDTO": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "integer"
                },
                "citizenship": {
                    "type": "string"
                },
                "destination_city": {
                    "type": "string"
                },
                "destination_country": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "event_interest": {
                    "type": "boolean"
                },
                "hotel_preferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "insurance_needed": {
                    "type": "boolean"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "origin_city": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "transport_type": {
                    "type": "string"
                },
                "travelers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.TravelerInput"
                    }
                },
                "trip_purpose": {
                    "type": "string"
                }
            }
        },
        "trip.ReviewSummary": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "source_link": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "target_name": {
                    "type": "string"
                }
            }
        },
        "trip.TodoItem": {
            "type": "object",
            "properties": {
                "day_label": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "trip.TodoSection": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.TodoItem"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "trip.TransportOption": {
            "type": "object",
            "properties": {
                "arrival": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "departure": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "selected": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "trip.Traveler": {
            "type": "object",
            "properties": {
                "age_group": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "preferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "trip.TravelerInput": {
            "type": "object",
            "required": [
                "age_group",
                "type"
            ],
            "properties": {
                "age_group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "preferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "trip.Trip": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.ActivityItem"
                    }
                },
                "budget": {
                    "$ref": "#/definitions/trip.BudgetSummary"
                },
                "chat_session_id": {
                    "type": "string"
                },
                "citizenship": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "destination_city": {
                    "type": "string"
                },
                "destination_country": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "event_interest": {
                    "type": "boolean"
                },
                "hotel_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.HotelOption"
                    }
                },
                "hotel_preferences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "insurance_needed": {
                    "type": "boolean"
                },
                "interests": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "offers": {
                    "$ref": "#/definitions/trip.OfferSummary"
                },
                "origin_city": {
                    "type": "string"
                },
                "review_summaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.ReviewSummary"
                    }
                },
                "selected_hotel": {
                    "$ref": "#/definitions/trip.HotelOption"
                },
                "selected_transport": {
                    "$ref": "#/definitions/trip.TransportOption"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "todo_sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.TodoSection"
                    }
                },
                "transport_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.TransportOption"
                    }
                },
                "transport_type": {
                    "type": "string"
                },
                "travelers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.Traveler"
                    }
                },
                "trip_purpose": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "vibe_labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "visa": {
                    "$ref": "#/definitions/trip.VisaInfo"
                }
            }
        },
        "trip.TripDetailsResponse": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.ActivityItem"
                    }
                },
                "budget": {
                    "$ref": "#/definitions/trip.BudgetSummary"
                },
                "chat_entrypoints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "offers": {
                    "$ref": "#/definitions/trip.OfferSummary"
                },
                "review_summaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.ReviewSummary"
                    }
                },
                "selected_hotel": {
                    "$ref": "#/definitions/trip.HotelOption"
                },
                "selected_transport": {
                    "$ref": "#/definitions/trip.TransportOption"
                },
                "todo_sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.TodoSection"
                    }
                },
                "travelers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/trip.Traveler"
                    }
                },
                "trip": {
                    "$ref": "#/definitions/trip.Trip"
                },
                "visa": {
                    "$ref": "#/definitions/trip.VisaInfo"
                }
            }
        },
        "trip.VisaInfo": {
            "type": "object",
            "properties": {
                "checklist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "country": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "recommended_lead": {
                    "type": "string"
                },
                "requirement": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Smart Travel Halyk Backend API",
	Description:      "JWT Token as Bearer: Authorization: Bearer {token}",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
